"""Read and write the ``<feature-audit>`` document format.

This is the per-file sidecar shape (one ``<feature-audit>`` per corpus file) and
the same shape the ``mx-api-feature-audit`` skill emits for ``mx::api``. Elements and
attributes are sorted so the output is stable and diff-friendly.

    <feature-audit>
      <audited>recsuite/Saltarello.xml</audited>
      <audited-version>3.0</audited-version>
      <features>
        <feature>
          <name>accidental</name>
          <attributes>
            <attribute>cautionary</attribute>
          </attributes>
        </feature>
        <feature>
          <name>barline</name>
        </feature>
      </features>
    </feature-audit>
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

from .extract import FileFeatures

# Note: XML comments may not contain a double hyphen, so this avoids spelling
# out the `--force` flag literally.
_GENERATED_NOTE = (
    "Generated by `python3 -m audit files`. The element/attribute surface of the\n"
    "     sibling corpus file. Do not edit by hand; regenerate with the audit tool."
)


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def render(ff: FileFeatures) -> str:
    """Render a ``FileFeatures`` to the ``<feature-audit>`` XML text."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- {_GENERATED_NOTE} -->",
        "<feature-audit>",
        f"  <audited>{_escape(ff.audited)}</audited>",
        f"  <audited-version>{_escape(ff.version)}</audited-version>",
        "  <features>",
    ]
    for name in sorted(ff.elements):
        attrs = sorted(ff.elements[name])
        if attrs:
            lines.append("    <feature>")
            lines.append(f"      <name>{_escape(name)}</name>")
            lines.append("      <attributes>")
            for a in attrs:
                lines.append(f"        <attribute>{_escape(a)}</attribute>")
            lines.append("      </attributes>")
            lines.append("    </feature>")
        else:
            lines.append("    <feature>")
            lines.append(f"      <name>{_escape(name)}</name>")
            lines.append("    </feature>")
    lines.append("  </features>")
    lines.append("</feature-audit>")
    lines.append("")
    return "\n".join(lines)


def write(ff: FileFeatures, path: Path) -> None:
    path.write_text(render(ff), encoding="utf-8")


def read(path: Path) -> FileFeatures:
    """Parse a ``<feature-audit>`` file back into a ``FileFeatures``."""
    root = ET.parse(path).getroot()
    ff = FileFeatures(
        audited=(root.findtext("audited") or "").strip(),
        version=(root.findtext("audited-version") or "").strip(),
        root="",
    )
    for feature in root.findall("./features/feature"):
        name = (feature.findtext("name") or "").strip()
        attrs = {
            (a.text or "").strip() for a in feature.findall("./attributes/attribute")
        }
        ff.elements[name] = {a for a in attrs if a}
    return ff
