FROM matthewjamesbriggs/mxci:v001

ENV BASEDIR="/mx"
WORKDIR $BASEDIR
COPY . .
CMD cmake \
    -DMX_BUILD_TESTS=on \
    -DMX_BUILD_CORE_TESTS=on \
    -DMX_BUILD_EXAMPLES=on \
    . && \
    make -j12 && \
    ./MxTest && \
    ./MxRead && \
    ./MxWrite
# CMD cmake --version