// MusicXML Class Library
// Copyright (c) by Matthew James Briggs
// Distributed under the MIT License

#pragma once

#include <iostream>
#include <string>

namespace mx
{
    namespace core
    {
        #define MX_ENUM_CLASS_NAME PlaybackSound

        #define MX_ENUM_MEMBERS( MX_ENUM_VALUE )      \
        MX_ENUM_VALUE( brassAlphorn, "brass.alphorn" ) \
        MX_ENUM_VALUE( brassAltoHorn, "brass.alto-horn" ) \
        MX_ENUM_VALUE( brassBaritoneHorn, "brass.baritone-horn" ) \
        MX_ENUM_VALUE( brassBugle, "brass.bugle" ) \
        MX_ENUM_VALUE( brassBugleAlto, "brass.bugle.alto" ) \
        MX_ENUM_VALUE( brassBugleBaritone, "brass.bugle.baritone" ) \
        MX_ENUM_VALUE( brassBugleContrabass, "brass.bugle.contrabass" ) \
        MX_ENUM_VALUE( brassBugleEuphoniumBugle, "brass.bugle.euphonium-bugle" ) \
        MX_ENUM_VALUE( brassBugleMellophoneBugle, "brass.bugle.mellophone-bugle" ) \
        MX_ENUM_VALUE( brassBugleSoprano, "brass.bugle.soprano" ) \
        MX_ENUM_VALUE( brassCimbasso, "brass.cimbasso" ) \
        MX_ENUM_VALUE( brassConchShell, "brass.conch-shell" ) \
        MX_ENUM_VALUE( brassCornet, "brass.cornet" ) \
        MX_ENUM_VALUE( brassCornetSoprano, "brass.cornet.soprano" ) \
        MX_ENUM_VALUE( brassCornett, "brass.cornett" ) \
        MX_ENUM_VALUE( brassCornettTenor, "brass.cornett.tenor" ) \
        MX_ENUM_VALUE( brassCornettino, "brass.cornettino" ) \
        MX_ENUM_VALUE( brassDidgeridoo, "brass.didgeridoo" ) \
        MX_ENUM_VALUE( brassEuphonium, "brass.euphonium" ) \
        MX_ENUM_VALUE( brassFiscorn, "brass.fiscorn" ) \
        MX_ENUM_VALUE( brassFlugelhorn, "brass.flugelhorn" ) \
        MX_ENUM_VALUE( brassFrenchHorn, "brass.french-horn" ) \
        MX_ENUM_VALUE( brassGroup, "brass.group" ) \
        MX_ENUM_VALUE( brassGroupSynth, "brass.group.synth" ) \
        MX_ENUM_VALUE( brassHelicon, "brass.helicon" ) \
        MX_ENUM_VALUE( brassHoragai, "brass.horagai" ) \
        MX_ENUM_VALUE( brassKuhlohorn, "brass.kuhlohorn" ) \
        MX_ENUM_VALUE( brassMellophone, "brass.mellophone" ) \
        MX_ENUM_VALUE( brassNaturalHorn, "brass.natural-horn" ) \
        MX_ENUM_VALUE( brassOphicleide, "brass.ophicleide" ) \
        MX_ENUM_VALUE( brassPosthorn, "brass.posthorn" ) \
        MX_ENUM_VALUE( brassRagDung, "brass.rag-dung" ) \
        MX_ENUM_VALUE( brassSackbutt, "brass.sackbutt" ) \
        MX_ENUM_VALUE( brassSackbuttAlto, "brass.sackbutt.alto" ) \
        MX_ENUM_VALUE( brassSackbuttBass, "brass.sackbutt.bass" ) \
        MX_ENUM_VALUE( brassSackbuttTenor, "brass.sackbutt.tenor" ) \
        MX_ENUM_VALUE( brassSaxhorn, "brass.saxhorn" ) \
        MX_ENUM_VALUE( brassSerpent, "brass.serpent" ) \
        MX_ENUM_VALUE( brassShofar, "brass.shofar" ) \
        MX_ENUM_VALUE( brassSousaphone, "brass.sousaphone" ) \
        MX_ENUM_VALUE( brassTrombone, "brass.trombone" ) \
        MX_ENUM_VALUE( brassTromboneAlto, "brass.trombone.alto" ) \
        MX_ENUM_VALUE( brassTromboneBass, "brass.trombone.bass" ) \
        MX_ENUM_VALUE( brassTromboneContrabass, "brass.trombone.contrabass" ) \
        MX_ENUM_VALUE( brassTromboneTenor, "brass.trombone.tenor" ) \
        MX_ENUM_VALUE( brassTrumpet, "brass.trumpet" ) \
        MX_ENUM_VALUE( brassTrumpetBaroque, "brass.trumpet.baroque" ) \
        MX_ENUM_VALUE( brassTrumpetBass, "brass.trumpet.bass" ) \
        MX_ENUM_VALUE( brassTrumpetBflat, "brass.trumpet.bflat" ) \
        MX_ENUM_VALUE( brassTrumpetC, "brass.trumpet.c" ) \
        MX_ENUM_VALUE( brassTrumpetD, "brass.trumpet.d" ) \
        MX_ENUM_VALUE( brassTrumpetPiccolo, "brass.trumpet.piccolo" ) \
        MX_ENUM_VALUE( brassTrumpetPocket, "brass.trumpet.pocket" ) \
        MX_ENUM_VALUE( brassTrumpetSlide, "brass.trumpet.slide" ) \
        MX_ENUM_VALUE( brassTrumpetTenor, "brass.trumpet.tenor" ) \
        MX_ENUM_VALUE( brassTuba, "brass.tuba" ) \
        MX_ENUM_VALUE( brassTubaBass, "brass.tuba.bass" ) \
        MX_ENUM_VALUE( brassTubaSubcontrabass, "brass.tuba.subcontrabass" ) \
        MX_ENUM_VALUE( brassViennaHorn, "brass.vienna-horn" ) \
        MX_ENUM_VALUE( brassVuvuzela, "brass.vuvuzela" ) \
        MX_ENUM_VALUE( brassWagnerTuba, "brass.wagner-tuba" ) \
        MX_ENUM_VALUE( drumApentemma, "drum.apentemma" ) \
        MX_ENUM_VALUE( drumAshiko, "drum.ashiko" ) \
        MX_ENUM_VALUE( drumAtabaque, "drum.atabaque" ) \
        MX_ENUM_VALUE( drumAtoke, "drum.atoke" ) \
        MX_ENUM_VALUE( drumAtsimevu, "drum.atsimevu" ) \
        MX_ENUM_VALUE( drumAxatse, "drum.axatse" ) \
        MX_ENUM_VALUE( drumBassDrum, "drum.bass-drum" ) \
        MX_ENUM_VALUE( drumBata, "drum.bata" ) \
        MX_ENUM_VALUE( drumBataItotele, "drum.bata.itotele" ) \
        MX_ENUM_VALUE( drumBataIya, "drum.bata.iya" ) \
        MX_ENUM_VALUE( drumBataOkonkolo, "drum.bata.okonkolo" ) \
        MX_ENUM_VALUE( drumBendir, "drum.bendir" ) \
        MX_ENUM_VALUE( drumBodhran, "drum.bodhran" ) \
        MX_ENUM_VALUE( drumBombo, "drum.bombo" ) \
        MX_ENUM_VALUE( drumBongo, "drum.bongo" ) \
        MX_ENUM_VALUE( drumBougarabou, "drum.bougarabou" ) \
        MX_ENUM_VALUE( drumBuffaloDrum, "drum.buffalo-drum" ) \
        MX_ENUM_VALUE( drumCajon, "drum.cajon" ) \
        MX_ENUM_VALUE( drumChenda, "drum.chenda" ) \
        MX_ENUM_VALUE( drumChuDaiko, "drum.chu-daiko" ) \
        MX_ENUM_VALUE( drumConga, "drum.conga" ) \
        MX_ENUM_VALUE( drumCuica, "drum.cuica" ) \
        MX_ENUM_VALUE( drumDabakan, "drum.dabakan" ) \
        MX_ENUM_VALUE( drumDaff, "drum.daff" ) \
        MX_ENUM_VALUE( drumDafli, "drum.dafli" ) \
        MX_ENUM_VALUE( drumDaibyosi, "drum.daibyosi" ) \
        MX_ENUM_VALUE( drumDamroo, "drum.damroo" ) \
        MX_ENUM_VALUE( drumDarabuka, "drum.darabuka" ) \
        MX_ENUM_VALUE( drumDef, "drum.def" ) \
        MX_ENUM_VALUE( drumDhol, "drum.dhol" ) \
        MX_ENUM_VALUE( drumDholak, "drum.dholak" ) \
        MX_ENUM_VALUE( drumDjembe, "drum.djembe" ) \
        MX_ENUM_VALUE( drumDoira, "drum.doira" ) \
        MX_ENUM_VALUE( drumDondo, "drum.dondo" ) \
        MX_ENUM_VALUE( drumDounDounBa, "drum.doun-doun-ba" ) \
        MX_ENUM_VALUE( drumDuff, "drum.duff" ) \
        MX_ENUM_VALUE( drumDumbek, "drum.dumbek" ) \
        MX_ENUM_VALUE( drumFontomfrom, "drum.fontomfrom" ) \
        MX_ENUM_VALUE( drumFrameDrum, "drum.frame-drum" ) \
        MX_ENUM_VALUE( drumFrameDrumArabian, "drum.frame-drum.arabian" ) \
        MX_ENUM_VALUE( drumGeduk, "drum.geduk" ) \
        MX_ENUM_VALUE( drumGhatam, "drum.ghatam" ) \
        MX_ENUM_VALUE( drumGome, "drum.gome" ) \
        MX_ENUM_VALUE( drumGroup, "drum.group" ) \
        MX_ENUM_VALUE( drumGroupChinese, "drum.group.chinese" ) \
        MX_ENUM_VALUE( drumGroupEwe, "drum.group.ewe" ) \
        MX_ENUM_VALUE( drumGroupIndian, "drum.group.indian" ) \
        MX_ENUM_VALUE( drumGroupSet, "drum.group.set" ) \
        MX_ENUM_VALUE( drumHandDrum, "drum.hand-drum" ) \
        MX_ENUM_VALUE( drumHiraDaiko, "drum.hira-daiko" ) \
        MX_ENUM_VALUE( drumIbo, "drum.ibo" ) \
        MX_ENUM_VALUE( drumIgihumurizo, "drum.igihumurizo" ) \
        MX_ENUM_VALUE( drumInyahura, "drum.inyahura" ) \
        MX_ENUM_VALUE( drumIshakwe, "drum.ishakwe" ) \
        MX_ENUM_VALUE( drumJangGu, "drum.jang-gu" ) \
        MX_ENUM_VALUE( drumKagan, "drum.kagan" ) \
        MX_ENUM_VALUE( drumKakko, "drum.kakko" ) \
        MX_ENUM_VALUE( drumKanjira, "drum.kanjira" ) \
        MX_ENUM_VALUE( drumKendhang, "drum.kendhang" ) \
        MX_ENUM_VALUE( drumKendhangAgeng, "drum.kendhang.ageng" ) \
        MX_ENUM_VALUE( drumKendhangCiblon, "drum.kendhang.ciblon" ) \
        MX_ENUM_VALUE( drumKenkeni, "drum.kenkeni" ) \
        MX_ENUM_VALUE( drumKhol, "drum.khol" ) \
        MX_ENUM_VALUE( drumKickDrum, "drum.kick-drum" ) \
        MX_ENUM_VALUE( drumKidi, "drum.kidi" ) \
        MX_ENUM_VALUE( drumKoDaiko, "drum.ko-daiko" ) \
        MX_ENUM_VALUE( drumKpanlogo, "drum.kpanlogo" ) \
        MX_ENUM_VALUE( drumKudum, "drum.kudum" ) \
        MX_ENUM_VALUE( drumLambeg, "drum.lambeg" ) \
        MX_ENUM_VALUE( drumLionDrum, "drum.lion-drum" ) \
        MX_ENUM_VALUE( drumLogDrum, "drum.log-drum" ) \
        MX_ENUM_VALUE( drumLogDrumAfrican, "drum.log-drum.african" ) \
        MX_ENUM_VALUE( drumLogDrumNative, "drum.log-drum.native" ) \
        MX_ENUM_VALUE( drumLogDrumNigerian, "drum.log-drum.nigerian" ) \
        MX_ENUM_VALUE( drumMadal, "drum.madal" ) \
        MX_ENUM_VALUE( drumMaddale, "drum.maddale" ) \
        MX_ENUM_VALUE( drumMridangam, "drum.mridangam" ) \
        MX_ENUM_VALUE( drumNaal, "drum.naal" ) \
        MX_ENUM_VALUE( drumNagadoDaiko, "drum.nagado-daiko" ) \
        MX_ENUM_VALUE( drumNagara, "drum.nagara" ) \
        MX_ENUM_VALUE( drumNaqara, "drum.naqara" ) \
        MX_ENUM_VALUE( drumODaiko, "drum.o-daiko" ) \
        MX_ENUM_VALUE( drumOkawa, "drum.okawa" ) \
        MX_ENUM_VALUE( drumOkedoDaiko, "drum.okedo-daiko" ) \
        MX_ENUM_VALUE( drumPahuHula, "drum.pahu-hula" ) \
        MX_ENUM_VALUE( drumPakhawaj, "drum.pakhawaj" ) \
        MX_ENUM_VALUE( drumPandeiro, "drum.pandeiro" ) \
        MX_ENUM_VALUE( drumPandero, "drum.pandero" ) \
        MX_ENUM_VALUE( drumPowwow, "drum.powwow" ) \
        MX_ENUM_VALUE( drumPueblo, "drum.pueblo" ) \
        MX_ENUM_VALUE( drumRepinique, "drum.repinique" ) \
        MX_ENUM_VALUE( drumRiq, "drum.riq" ) \
        MX_ENUM_VALUE( drumRototom, "drum.rototom" ) \
        MX_ENUM_VALUE( drumSabar, "drum.sabar" ) \
        MX_ENUM_VALUE( drumSakara, "drum.sakara" ) \
        MX_ENUM_VALUE( drumSampho, "drum.sampho" ) \
        MX_ENUM_VALUE( drumSangban, "drum.sangban" ) \
        MX_ENUM_VALUE( drumShimeDaiko, "drum.shime-daiko" ) \
        MX_ENUM_VALUE( drumSlitDrum, "drum.slit-drum" ) \
        MX_ENUM_VALUE( drumSlitDrumKrin, "drum.slit-drum.krin" ) \
        MX_ENUM_VALUE( drumSnareDrum, "drum.snare-drum" ) \
        MX_ENUM_VALUE( drumSnareDrumElectric, "drum.snare-drum.electric" ) \
        MX_ENUM_VALUE( drumSogo, "drum.sogo" ) \
        MX_ENUM_VALUE( drumSurdo, "drum.surdo" ) \
        MX_ENUM_VALUE( drumTabla, "drum.tabla" ) \
        MX_ENUM_VALUE( drumTablaBayan, "drum.tabla.bayan" ) \
        MX_ENUM_VALUE( drumTablaDayan, "drum.tabla.dayan" ) \
        MX_ENUM_VALUE( drumTaiko, "drum.taiko" ) \
        MX_ENUM_VALUE( drumTalking, "drum.talking" ) \
        MX_ENUM_VALUE( drumTama, "drum.tama" ) \
        MX_ENUM_VALUE( drumTamborita, "drum.tamborita" ) \
        MX_ENUM_VALUE( drumTambourine, "drum.tambourine" ) \
        MX_ENUM_VALUE( drumTamte, "drum.tamte" ) \
        MX_ENUM_VALUE( drumTangku, "drum.tangku" ) \
        MX_ENUM_VALUE( drumTanTan, "drum.tan-tan" ) \
        MX_ENUM_VALUE( drumTaphon, "drum.taphon" ) \
        MX_ENUM_VALUE( drumTar, "drum.tar" ) \
        MX_ENUM_VALUE( drumTasha, "drum.tasha" ) \
        MX_ENUM_VALUE( drumTenorDrum, "drum.tenor-drum" ) \
        MX_ENUM_VALUE( drumTeponaxtli, "drum.teponaxtli" ) \
        MX_ENUM_VALUE( drumThavil, "drum.thavil" ) \
        MX_ENUM_VALUE( drumTheBox, "drum.the-box" ) \
        MX_ENUM_VALUE( drumTimbale, "drum.timbale" ) \
        MX_ENUM_VALUE( drumTimpani, "drum.timpani" ) \
        MX_ENUM_VALUE( drumTinaja, "drum.tinaja" ) \
        MX_ENUM_VALUE( drumToere, "drum.toere" ) \
        MX_ENUM_VALUE( drumTombak, "drum.tombak" ) \
        MX_ENUM_VALUE( drumTomTom, "drum.tom-tom" ) \
        MX_ENUM_VALUE( drumTomTomSynth, "drum.tom-tom.synth" ) \
        MX_ENUM_VALUE( drumTsuzumi, "drum.tsuzumi" ) \
        MX_ENUM_VALUE( drumTumbak, "drum.tumbak" ) \
        MX_ENUM_VALUE( drumUchiwaDaiko, "drum.uchiwa-daiko" ) \
        MX_ENUM_VALUE( drumUdaku, "drum.udaku" ) \
        MX_ENUM_VALUE( drumUdu, "drum.udu" ) \
        MX_ENUM_VALUE( drumZarb, "drum.zarb" ) \
        MX_ENUM_VALUE( effectAeolianHarp, "effect.aeolian-harp" ) \
        MX_ENUM_VALUE( effectAirHorn, "effect.air-horn" ) \
        MX_ENUM_VALUE( effectApplause, "effect.applause" ) \
        MX_ENUM_VALUE( effectBassStringSlap, "effect.bass-string-slap" ) \
        MX_ENUM_VALUE( effectBird, "effect.bird" ) \
        MX_ENUM_VALUE( effectBirdNightingale, "effect.bird.nightingale" ) \
        MX_ENUM_VALUE( effectBirdTweet, "effect.bird.tweet" ) \
        MX_ENUM_VALUE( effectBreath, "effect.breath" ) \
        MX_ENUM_VALUE( effectBubble, "effect.bubble" ) \
        MX_ENUM_VALUE( effectBullroarer, "effect.bullroarer" ) \
        MX_ENUM_VALUE( effectBurst, "effect.burst" ) \
        MX_ENUM_VALUE( effectCar, "effect.car" ) \
        MX_ENUM_VALUE( effectCarCrash, "effect.car.crash" ) \
        MX_ENUM_VALUE( effectCarEngine, "effect.car.engine" ) \
        MX_ENUM_VALUE( effectCarPass, "effect.car.pass" ) \
        MX_ENUM_VALUE( effectCarStop, "effect.car.stop" ) \
        MX_ENUM_VALUE( effectCrickets, "effect.crickets" ) \
        MX_ENUM_VALUE( effectDog, "effect.dog" ) \
        MX_ENUM_VALUE( effectDoorCreak, "effect.door.creak" ) \
        MX_ENUM_VALUE( effectDoorSlam, "effect.door.slam" ) \
        MX_ENUM_VALUE( effectExplosion, "effect.explosion" ) \
        MX_ENUM_VALUE( effectFluteKeyClick, "effect.flute-key-click" ) \
        MX_ENUM_VALUE( effectFootsteps, "effect.footsteps" ) \
        MX_ENUM_VALUE( effectFrogs, "effect.frogs" ) \
        MX_ENUM_VALUE( effectGuitarCutting, "effect.guitar-cutting" ) \
        MX_ENUM_VALUE( effectGuitarFret, "effect.guitar-fret" ) \
        MX_ENUM_VALUE( effectGunshot, "effect.gunshot" ) \
        MX_ENUM_VALUE( effectHandClap, "effect.hand-clap" ) \
        MX_ENUM_VALUE( effectHeartbeat, "effect.heartbeat" ) \
        MX_ENUM_VALUE( effectHelicopter, "effect.helicopter" ) \
        MX_ENUM_VALUE( effectHighQ, "effect.high-q" ) \
        MX_ENUM_VALUE( effectHorseGallop, "effect.horse-gallop" ) \
        MX_ENUM_VALUE( effectJetPlane, "effect.jet-plane" ) \
        MX_ENUM_VALUE( effectLaserGun, "effect.laser-gun" ) \
        MX_ENUM_VALUE( effectLaugh, "effect.laugh" ) \
        MX_ENUM_VALUE( effectLionsRoar, "effect.lions-roar" ) \
        MX_ENUM_VALUE( effectMachineGun, "effect.machine-gun" ) \
        MX_ENUM_VALUE( effectMarchingMachine, "effect.marching-machine" ) \
        MX_ENUM_VALUE( effectMetronomeBell, "effect.metronome-bell" ) \
        MX_ENUM_VALUE( effectMetronomeClick, "effect.metronome-click" ) \
        MX_ENUM_VALUE( effectPat, "effect.pat" ) \
        MX_ENUM_VALUE( effectPunch, "effect.punch" ) \
        MX_ENUM_VALUE( effectRain, "effect.rain" ) \
        MX_ENUM_VALUE( effectScratch, "effect.scratch" ) \
        MX_ENUM_VALUE( effectScream, "effect.scream" ) \
        MX_ENUM_VALUE( effectSeashore, "effect.seashore" ) \
        MX_ENUM_VALUE( effectSiren, "effect.siren" ) \
        MX_ENUM_VALUE( effectSlap, "effect.slap" ) \
        MX_ENUM_VALUE( effectSnap, "effect.snap" ) \
        MX_ENUM_VALUE( effectStamp, "effect.stamp" ) \
        MX_ENUM_VALUE( effectStarship, "effect.starship" ) \
        MX_ENUM_VALUE( effectStream, "effect.stream" ) \
        MX_ENUM_VALUE( effectTelephoneRing, "effect.telephone-ring" ) \
        MX_ENUM_VALUE( effectThunder, "effect.thunder" ) \
        MX_ENUM_VALUE( effectTrain, "effect.train" ) \
        MX_ENUM_VALUE( effectTrashCan, "effect.trash-can" ) \
        MX_ENUM_VALUE( effectWhip, "effect.whip" ) \
        MX_ENUM_VALUE( effectWhistle, "effect.whistle" ) \
        MX_ENUM_VALUE( effectWhistleMouthSiren, "effect.whistle.mouth-siren" ) \
        MX_ENUM_VALUE( effectWhistlePolice, "effect.whistle.police" ) \
        MX_ENUM_VALUE( effectWhistleSlide, "effect.whistle.slide" ) \
        MX_ENUM_VALUE( effectWhistleTrain, "effect.whistle.train" ) \
        MX_ENUM_VALUE( effectWind, "effect.wind" ) \
        MX_ENUM_VALUE( keyboardAccordion, "keyboard.accordion" ) \
        MX_ENUM_VALUE( keyboardBandoneon, "keyboard.bandoneon" ) \
        MX_ENUM_VALUE( keyboardCelesta, "keyboard.celesta" ) \
        MX_ENUM_VALUE( keyboardClavichord, "keyboard.clavichord" ) \
        MX_ENUM_VALUE( keyboardClavichordSynth, "keyboard.clavichord.synth" ) \
        MX_ENUM_VALUE( keyboardConcertina, "keyboard.concertina" ) \
        MX_ENUM_VALUE( keyboardFortepiano, "keyboard.fortepiano" ) \
        MX_ENUM_VALUE( keyboardHarmonium, "keyboard.harmonium" ) \
        MX_ENUM_VALUE( keyboardHarpsichord, "keyboard.harpsichord" ) \
        MX_ENUM_VALUE( keyboardOndesMartenot, "keyboard.ondes-martenot" ) \
        MX_ENUM_VALUE( keyboardOrgan, "keyboard.organ" ) \
        MX_ENUM_VALUE( keyboardOrganDrawbar, "keyboard.organ.drawbar" ) \
        MX_ENUM_VALUE( keyboardOrganPercussive, "keyboard.organ.percussive" ) \
        MX_ENUM_VALUE( keyboardOrganPipe, "keyboard.organ.pipe" ) \
        MX_ENUM_VALUE( keyboardOrganReed, "keyboard.organ.reed" ) \
        MX_ENUM_VALUE( keyboardOrganRotary, "keyboard.organ.rotary" ) \
        MX_ENUM_VALUE( keyboardPiano, "keyboard.piano" ) \
        MX_ENUM_VALUE( keyboardPianoElectric, "keyboard.piano.electric" ) \
        MX_ENUM_VALUE( keyboardPianoGrand, "keyboard.piano.grand" ) \
        MX_ENUM_VALUE( keyboardPianoHonkyTonk, "keyboard.piano.honky-tonk" ) \
        MX_ENUM_VALUE( keyboardPianoPrepared, "keyboard.piano.prepared" ) \
        MX_ENUM_VALUE( keyboardPianoToy, "keyboard.piano.toy" ) \
        MX_ENUM_VALUE( keyboardPianoUpright, "keyboard.piano.upright" ) \
        MX_ENUM_VALUE( keyboardVirginal, "keyboard.virginal" ) \
        MX_ENUM_VALUE( metalAdodo, "metal.adodo" ) \
        MX_ENUM_VALUE( metalAnvil, "metal.anvil" ) \
        MX_ENUM_VALUE( metalBabendil, "metal.babendil" ) \
        MX_ENUM_VALUE( metalBellsAgogo, "metal.bells.agogo" ) \
        MX_ENUM_VALUE( metalBellsAlmglocken, "metal.bells.almglocken" ) \
        MX_ENUM_VALUE( metalBellsBellPlate, "metal.bells.bell-plate" ) \
        MX_ENUM_VALUE( metalBellsBellTree, "metal.bells.bell-tree" ) \
        MX_ENUM_VALUE( metalBellsCarillon, "metal.bells.carillon" ) \
        MX_ENUM_VALUE( metalBellsChimes, "metal.bells.chimes" ) \
        MX_ENUM_VALUE( metalBellsChimta, "metal.bells.chimta" ) \
        MX_ENUM_VALUE( metalBellsChippli, "metal.bells.chippli" ) \
        MX_ENUM_VALUE( metalBellsChurch, "metal.bells.church" ) \
        MX_ENUM_VALUE( metalBellsCowbell, "metal.bells.cowbell" ) \
        MX_ENUM_VALUE( metalBellsDawuro, "metal.bells.dawuro" ) \
        MX_ENUM_VALUE( metalBellsGankokwe, "metal.bells.gankokwe" ) \
        MX_ENUM_VALUE( metalBellsGhungroo, "metal.bells.ghungroo" ) \
        MX_ENUM_VALUE( metalBellsHatheli, "metal.bells.hatheli" ) \
        MX_ENUM_VALUE( metalBellsJingleBell, "metal.bells.jingle-bell" ) \
        MX_ENUM_VALUE( metalBellsKhartal, "metal.bells.khartal" ) \
        MX_ENUM_VALUE( metalBellsMarkTree, "metal.bells.mark-tree" ) \
        MX_ENUM_VALUE( metalBellsSistrum, "metal.bells.sistrum" ) \
        MX_ENUM_VALUE( metalBellsSleighBells, "metal.bells.sleigh-bells" ) \
        MX_ENUM_VALUE( metalBellsTemple, "metal.bells.temple" ) \
        MX_ENUM_VALUE( metalBellsTibetan, "metal.bells.tibetan" ) \
        MX_ENUM_VALUE( metalBellsTinklebell, "metal.bells.tinklebell" ) \
        MX_ENUM_VALUE( metalBellsTrychel, "metal.bells.trychel" ) \
        MX_ENUM_VALUE( metalBellsWindChimes, "metal.bells.wind-chimes" ) \
        MX_ENUM_VALUE( metalBellsZills, "metal.bells.zills" ) \
        MX_ENUM_VALUE( metalBerimbau, "metal.berimbau" ) \
        MX_ENUM_VALUE( metalBrakeDrums, "metal.brake-drums" ) \
        MX_ENUM_VALUE( metalCrotales, "metal.crotales" ) \
        MX_ENUM_VALUE( metalCymbalBo, "metal.cymbal.bo" ) \
        MX_ENUM_VALUE( metalCymbalCengCeng, "metal.cymbal.ceng-ceng" ) \
        MX_ENUM_VALUE( metalCymbalChabara, "metal.cymbal.chabara" ) \
        MX_ENUM_VALUE( metalCymbalChinese, "metal.cymbal.chinese" ) \
        MX_ENUM_VALUE( metalCymbalChing, "metal.cymbal.ching" ) \
        MX_ENUM_VALUE( metalCymbalClash, "metal.cymbal.clash" ) \
        MX_ENUM_VALUE( metalCymbalCrash, "metal.cymbal.crash" ) \
        MX_ENUM_VALUE( metalCymbalFinger, "metal.cymbal.finger" ) \
        MX_ENUM_VALUE( metalCymbalHand, "metal.cymbal.hand" ) \
        MX_ENUM_VALUE( metalCymbalKesi, "metal.cymbal.kesi" ) \
        MX_ENUM_VALUE( metalCymbalManjeera, "metal.cymbal.manjeera" ) \
        MX_ENUM_VALUE( metalCymbalReverse, "metal.cymbal.reverse" ) \
        MX_ENUM_VALUE( metalCymbalRide, "metal.cymbal.ride" ) \
        MX_ENUM_VALUE( metalCymbalSizzle, "metal.cymbal.sizzle" ) \
        MX_ENUM_VALUE( metalCymbalSplash, "metal.cymbal.splash" ) \
        MX_ENUM_VALUE( metalCymbalSuspended, "metal.cymbal.suspended" ) \
        MX_ENUM_VALUE( metalCymbalTebyoshi, "metal.cymbal.tebyoshi" ) \
        MX_ENUM_VALUE( metalCymbalTibetan, "metal.cymbal.tibetan" ) \
        MX_ENUM_VALUE( metalCymbalTingsha, "metal.cymbal.tingsha" ) \
        MX_ENUM_VALUE( metalFlexatone, "metal.flexatone" ) \
        MX_ENUM_VALUE( metalGong, "metal.gong" ) \
        MX_ENUM_VALUE( metalGongAgeng, "metal.gong.ageng" ) \
        MX_ENUM_VALUE( metalGongAgung, "metal.gong.agung" ) \
        MX_ENUM_VALUE( metalGongChanchiki, "metal.gong.chanchiki" ) \
        MX_ENUM_VALUE( metalGongChinese, "metal.gong.chinese" ) \
        MX_ENUM_VALUE( metalGongGandingan, "metal.gong.gandingan" ) \
        MX_ENUM_VALUE( metalGongKempul, "metal.gong.kempul" ) \
        MX_ENUM_VALUE( metalGongKempyang, "metal.gong.kempyang" ) \
        MX_ENUM_VALUE( metalGongKetuk, "metal.gong.ketuk" ) \
        MX_ENUM_VALUE( metalGongKkwenggwari, "metal.gong.kkwenggwari" ) \
        MX_ENUM_VALUE( metalGongLuo, "metal.gong.luo" ) \
        MX_ENUM_VALUE( metalGongSinging, "metal.gong.singing" ) \
        MX_ENUM_VALUE( metalGongThai, "metal.gong.thai" ) \
        MX_ENUM_VALUE( metalGuira, "metal.guira" ) \
        MX_ENUM_VALUE( metalHang, "metal.hang" ) \
        MX_ENUM_VALUE( metalHiHat, "metal.hi-hat" ) \
        MX_ENUM_VALUE( metalJawHarp, "metal.jaw-harp" ) \
        MX_ENUM_VALUE( metalKengong, "metal.kengong" ) \
        MX_ENUM_VALUE( metalMurchang, "metal.murchang" ) \
        MX_ENUM_VALUE( metalMusicalSaw, "metal.musical-saw" ) \
        MX_ENUM_VALUE( metalSingingBowl, "metal.singing-bowl" ) \
        MX_ENUM_VALUE( metalSpoons, "metal.spoons" ) \
        MX_ENUM_VALUE( metalSteelDrums, "metal.steel-drums" ) \
        MX_ENUM_VALUE( metalTamtam, "metal.tamtam" ) \
        MX_ENUM_VALUE( metalThundersheet, "metal.thundersheet" ) \
        MX_ENUM_VALUE( metalTriangle, "metal.triangle" ) \
        MX_ENUM_VALUE( metalWashboard, "metal.washboard" ) \
        MX_ENUM_VALUE( pitchedPercussionAngklung, "pitched-percussion.angklung" ) \
        MX_ENUM_VALUE( pitchedPercussionBalafon, "pitched-percussion.balafon" ) \
        MX_ENUM_VALUE( pitchedPercussionBellLyre, "pitched-percussion.bell-lyre" ) \
        MX_ENUM_VALUE( pitchedPercussionBells, "pitched-percussion.bells" ) \
        MX_ENUM_VALUE( pitchedPercussionBianqing, "pitched-percussion.bianqing" ) \
        MX_ENUM_VALUE( pitchedPercussionBianzhong, "pitched-percussion.bianzhong" ) \
        MX_ENUM_VALUE( pitchedPercussionBonang, "pitched-percussion.bonang" ) \
        MX_ENUM_VALUE( pitchedPercussionCimbalom, "pitched-percussion.cimbalom" ) \
        MX_ENUM_VALUE( pitchedPercussionCrystalGlasses, "pitched-percussion.crystal-glasses" ) \
        MX_ENUM_VALUE( pitchedPercussionDanTamThapLuc, "pitched-percussion.dan-tam-thap-luc" ) \
        MX_ENUM_VALUE( pitchedPercussionFangxiang, "pitched-percussion.fangxiang" ) \
        MX_ENUM_VALUE( pitchedPercussionGandinganAKayo, "pitched-percussion.gandingan-a-kayo" ) \
        MX_ENUM_VALUE( pitchedPercussionGangsa, "pitched-percussion.gangsa" ) \
        MX_ENUM_VALUE( pitchedPercussionGender, "pitched-percussion.gender" ) \
        MX_ENUM_VALUE( pitchedPercussionGiying, "pitched-percussion.giying" ) \
        MX_ENUM_VALUE( pitchedPercussionGlassHarmonica, "pitched-percussion.glass-harmonica" ) \
        MX_ENUM_VALUE( pitchedPercussionGlockenspiel, "pitched-percussion.glockenspiel" ) \
        MX_ENUM_VALUE( pitchedPercussionGlockenspielAlto, "pitched-percussion.glockenspiel.alto" ) \
        MX_ENUM_VALUE( pitchedPercussionGlockenspielSoprano, "pitched-percussion.glockenspiel.soprano" ) \
        MX_ENUM_VALUE( pitchedPercussionGyil, "pitched-percussion.gyil" ) \
        MX_ENUM_VALUE( pitchedPercussionHammerDulcimer, "pitched-percussion.hammer-dulcimer" ) \
        MX_ENUM_VALUE( pitchedPercussionHandbells, "pitched-percussion.handbells" ) \
        MX_ENUM_VALUE( pitchedPercussionKalimba, "pitched-percussion.kalimba" ) \
        MX_ENUM_VALUE( pitchedPercussionKantil, "pitched-percussion.kantil" ) \
        MX_ENUM_VALUE( pitchedPercussionKhim, "pitched-percussion.khim" ) \
        MX_ENUM_VALUE( pitchedPercussionKulintang, "pitched-percussion.kulintang" ) \
        MX_ENUM_VALUE( pitchedPercussionKulintangAKayo, "pitched-percussion.kulintang-a-kayo" ) \
        MX_ENUM_VALUE( pitchedPercussionKulintangATiniok, "pitched-percussion.kulintang-a-tiniok" ) \
        MX_ENUM_VALUE( pitchedPercussionLikembe, "pitched-percussion.likembe" ) \
        MX_ENUM_VALUE( pitchedPercussionLuntang, "pitched-percussion.luntang" ) \
        MX_ENUM_VALUE( pitchedPercussionMarimba, "pitched-percussion.marimba" ) \
        MX_ENUM_VALUE( pitchedPercussionMarimbaBass, "pitched-percussion.marimba.bass" ) \
        MX_ENUM_VALUE( pitchedPercussionMbira, "pitched-percussion.mbira" ) \
        MX_ENUM_VALUE( pitchedPercussionMbiraArray, "pitched-percussion.mbira.array" ) \
        MX_ENUM_VALUE( pitchedPercussionMetallophone, "pitched-percussion.metallophone" ) \
        MX_ENUM_VALUE( pitchedPercussionMetallophoneAlto, "pitched-percussion.metallophone.alto" ) \
        MX_ENUM_VALUE( pitchedPercussionMetallophoneBass, "pitched-percussion.metallophone.bass" ) \
        MX_ENUM_VALUE( pitchedPercussionMetallophoneSoprano, "pitched-percussion.metallophone.soprano" ) \
        MX_ENUM_VALUE( pitchedPercussionMusicBox, "pitched-percussion.music-box" ) \
        MX_ENUM_VALUE( pitchedPercussionPelogPanerus, "pitched-percussion.pelog-panerus" ) \
        MX_ENUM_VALUE( pitchedPercussionPemade, "pitched-percussion.pemade" ) \
        MX_ENUM_VALUE( pitchedPercussionPenyacah, "pitched-percussion.penyacah" ) \
        MX_ENUM_VALUE( pitchedPercussionRanatEk, "pitched-percussion.ranat.ek" ) \
        MX_ENUM_VALUE( pitchedPercussionRanatEkLek, "pitched-percussion.ranat.ek-lek" ) \
        MX_ENUM_VALUE( pitchedPercussionRanatThum, "pitched-percussion.ranat.thum" ) \
        MX_ENUM_VALUE( pitchedPercussionRanatThumLek, "pitched-percussion.ranat.thum-lek" ) \
        MX_ENUM_VALUE( pitchedPercussionReyong, "pitched-percussion.reyong" ) \
        MX_ENUM_VALUE( pitchedPercussionSanza, "pitched-percussion.sanza" ) \
        MX_ENUM_VALUE( pitchedPercussionSaronBarung, "pitched-percussion.saron-barung" ) \
        MX_ENUM_VALUE( pitchedPercussionSaronDemong, "pitched-percussion.saron-demong" ) \
        MX_ENUM_VALUE( pitchedPercussionSaronPanerus, "pitched-percussion.saron-panerus" ) \
        MX_ENUM_VALUE( pitchedPercussionSlendroPanerus, "pitched-percussion.slendro-panerus" ) \
        MX_ENUM_VALUE( pitchedPercussionSlentem, "pitched-percussion.slentem" ) \
        MX_ENUM_VALUE( pitchedPercussionTsymbaly, "pitched-percussion.tsymbaly" ) \
        MX_ENUM_VALUE( pitchedPercussionTubes, "pitched-percussion.tubes" ) \
        MX_ENUM_VALUE( pitchedPercussionTubularBells, "pitched-percussion.tubular-bells" ) \
        MX_ENUM_VALUE( pitchedPercussionVibraphone, "pitched-percussion.vibraphone" ) \
        MX_ENUM_VALUE( pitchedPercussionXylophone, "pitched-percussion.xylophone" ) \
        MX_ENUM_VALUE( pitchedPercussionXylophoneAlto, "pitched-percussion.xylophone.alto" ) \
        MX_ENUM_VALUE( pitchedPercussionXylophoneBass, "pitched-percussion.xylophone.bass" ) \
        MX_ENUM_VALUE( pitchedPercussionXylophoneSoprano, "pitched-percussion.xylophone.soprano" ) \
        MX_ENUM_VALUE( pitchedPercussionXylorimba, "pitched-percussion.xylorimba" ) \
        MX_ENUM_VALUE( pitchedPercussionYangqin, "pitched-percussion.yangqin" ) \
        MX_ENUM_VALUE( pluckArchlute, "pluck.archlute" ) \
        MX_ENUM_VALUE( pluckAutoharp, "pluck.autoharp" ) \
        MX_ENUM_VALUE( pluckBaglama, "pluck.baglama" ) \
        MX_ENUM_VALUE( pluckBajo, "pluck.bajo" ) \
        MX_ENUM_VALUE( pluckBalalaika, "pluck.balalaika" ) \
        MX_ENUM_VALUE( pluckBalalaikaAlto, "pluck.balalaika.alto" ) \
        MX_ENUM_VALUE( pluckBalalaikaBass, "pluck.balalaika.bass" ) \
        MX_ENUM_VALUE( pluckBalalaikaContrabass, "pluck.balalaika.contrabass" ) \
        MX_ENUM_VALUE( pluckBalalaikaPiccolo, "pluck.balalaika.piccolo" ) \
        MX_ENUM_VALUE( pluckBalalaikaPrima, "pluck.balalaika.prima" ) \
        MX_ENUM_VALUE( pluckBalalaikaSecunda, "pluck.balalaika.secunda" ) \
        MX_ENUM_VALUE( pluckBandola, "pluck.bandola" ) \
        MX_ENUM_VALUE( pluckBandura, "pluck.bandura" ) \
        MX_ENUM_VALUE( pluckBandurria, "pluck.bandurria" ) \
        MX_ENUM_VALUE( pluckBanjo, "pluck.banjo" ) \
        MX_ENUM_VALUE( pluckBanjoTenor, "pluck.banjo.tenor" ) \
        MX_ENUM_VALUE( pluckBanjolele, "pluck.banjolele" ) \
        MX_ENUM_VALUE( pluckBarbat, "pluck.barbat" ) \
        MX_ENUM_VALUE( pluckBass, "pluck.bass" ) \
        MX_ENUM_VALUE( pluckBassAcoustic, "pluck.bass.acoustic" ) \
        MX_ENUM_VALUE( pluckBassBolon, "pluck.bass.bolon" ) \
        MX_ENUM_VALUE( pluckBassElectric, "pluck.bass.electric" ) \
        MX_ENUM_VALUE( pluckBassFretless, "pluck.bass.fretless" ) \
        MX_ENUM_VALUE( pluckBassGuitarron, "pluck.bass.guitarron" ) \
        MX_ENUM_VALUE( pluckBassSynth, "pluck.bass.synth" ) \
        MX_ENUM_VALUE( pluckBassSynthLead, "pluck.bass.synth.lead" ) \
        MX_ENUM_VALUE( pluckBassWashtub, "pluck.bass.washtub" ) \
        MX_ENUM_VALUE( pluckBassWhamola, "pluck.bass.whamola" ) \
        MX_ENUM_VALUE( pluckBegena, "pluck.begena" ) \
        MX_ENUM_VALUE( pluckBiwa, "pluck.biwa" ) \
        MX_ENUM_VALUE( pluckBordonua, "pluck.bordonua" ) \
        MX_ENUM_VALUE( pluckBouzouki, "pluck.bouzouki" ) \
        MX_ENUM_VALUE( pluckBouzoukiIrish, "pluck.bouzouki.irish" ) \
        MX_ENUM_VALUE( pluckCelticHarp, "pluck.celtic-harp" ) \
        MX_ENUM_VALUE( pluckCharango, "pluck.charango" ) \
        MX_ENUM_VALUE( pluckChitarraBattente, "pluck.chitarra-battente" ) \
        MX_ENUM_VALUE( pluckCithara, "pluck.cithara" ) \
        MX_ENUM_VALUE( pluckCittern, "pluck.cittern" ) \
        MX_ENUM_VALUE( pluckCuatro, "pluck.cuatro" ) \
        MX_ENUM_VALUE( pluckDanBau, "pluck.dan-bau" ) \
        MX_ENUM_VALUE( pluckDanNguyet, "pluck.dan-nguyet" ) \
        MX_ENUM_VALUE( pluckDanTranh, "pluck.dan-tranh" ) \
        MX_ENUM_VALUE( pluckDanTyBa, "pluck.dan-ty-ba" ) \
        MX_ENUM_VALUE( pluckDiddleyBow, "pluck.diddley-bow" ) \
        MX_ENUM_VALUE( pluckDomra, "pluck.domra" ) \
        MX_ENUM_VALUE( pluckDomu, "pluck.domu" ) \
        MX_ENUM_VALUE( pluckDulcimer, "pluck.dulcimer" ) \
        MX_ENUM_VALUE( pluckDutar, "pluck.dutar" ) \
        MX_ENUM_VALUE( pluckDuxianqin, "pluck.duxianqin" ) \
        MX_ENUM_VALUE( pluckEktara, "pluck.ektara" ) \
        MX_ENUM_VALUE( pluckGeomungo, "pluck.geomungo" ) \
        MX_ENUM_VALUE( pluckGottuvadhyam, "pluck.gottuvadhyam" ) \
        MX_ENUM_VALUE( pluckGuitar, "pluck.guitar" ) \
        MX_ENUM_VALUE( pluckGuitarAcoustic, "pluck.guitar.acoustic" ) \
        MX_ENUM_VALUE( pluckGuitarElectric, "pluck.guitar.electric" ) \
        MX_ENUM_VALUE( pluckGuitarNylonString, "pluck.guitar.nylon-string" ) \
        MX_ENUM_VALUE( pluckGuitarPedalSteel, "pluck.guitar.pedal-steel" ) \
        MX_ENUM_VALUE( pluckGuitarPortuguese, "pluck.guitar.portuguese" ) \
        MX_ENUM_VALUE( pluckGuitarRequinto, "pluck.guitar.requinto" ) \
        MX_ENUM_VALUE( pluckGuitarResonator, "pluck.guitar.resonator" ) \
        MX_ENUM_VALUE( pluckGuitarSteelString, "pluck.guitar.steel-string" ) \
        MX_ENUM_VALUE( pluckGuitjo, "pluck.guitjo" ) \
        MX_ENUM_VALUE( pluckGuitjoDoubleNeck, "pluck.guitjo.double-neck" ) \
        MX_ENUM_VALUE( pluckGuqin, "pluck.guqin" ) \
        MX_ENUM_VALUE( pluckGuzheng, "pluck.guzheng" ) \
        MX_ENUM_VALUE( pluckGuzhengChoazhou, "pluck.guzheng.choazhou" ) \
        MX_ENUM_VALUE( pluckHarp, "pluck.harp" ) \
        MX_ENUM_VALUE( pluckHarpGuitar, "pluck.harp-guitar" ) \
        MX_ENUM_VALUE( pluckHuapanguera, "pluck.huapanguera" ) \
        MX_ENUM_VALUE( pluckJaranaHuasteca, "pluck.jarana-huasteca" ) \
        MX_ENUM_VALUE( pluckJaranaJarocha, "pluck.jarana-jarocha" ) \
        MX_ENUM_VALUE( pluckJaranaJarochaMosquito, "pluck.jarana-jarocha.mosquito" ) \
        MX_ENUM_VALUE( pluckJaranaJarochaPrimera, "pluck.jarana-jarocha.primera" ) \
        MX_ENUM_VALUE( pluckJaranaJarochaSegunda, "pluck.jarana-jarocha.segunda" ) \
        MX_ENUM_VALUE( pluckJaranaJarochaTercera, "pluck.jarana-jarocha.tercera" ) \
        MX_ENUM_VALUE( pluckKabosy, "pluck.kabosy" ) \
        MX_ENUM_VALUE( pluckKantele, "pluck.kantele" ) \
        MX_ENUM_VALUE( pluckKanun, "pluck.kanun" ) \
        MX_ENUM_VALUE( pluckKayagum, "pluck.kayagum" ) \
        MX_ENUM_VALUE( pluckKobza, "pluck.kobza" ) \
        MX_ENUM_VALUE( pluckKomuz, "pluck.komuz" ) \
        MX_ENUM_VALUE( pluckKora, "pluck.kora" ) \
        MX_ENUM_VALUE( pluckKoto, "pluck.koto" ) \
        MX_ENUM_VALUE( pluckKutiyapi, "pluck.kutiyapi" ) \
        MX_ENUM_VALUE( pluckLangeleik, "pluck.langeleik" ) \
        MX_ENUM_VALUE( pluckLaud, "pluck.laud" ) \
        MX_ENUM_VALUE( pluckLute, "pluck.lute" ) \
        MX_ENUM_VALUE( pluckLyre, "pluck.lyre" ) \
        MX_ENUM_VALUE( pluckMandobass, "pluck.mandobass" ) \
        MX_ENUM_VALUE( pluckMandocello, "pluck.mandocello" ) \
        MX_ENUM_VALUE( pluckMandola, "pluck.mandola" ) \
        MX_ENUM_VALUE( pluckMandolin, "pluck.mandolin" ) \
        MX_ENUM_VALUE( pluckMandolinOctave, "pluck.mandolin.octave" ) \
        MX_ENUM_VALUE( pluckMandora, "pluck.mandora" ) \
        MX_ENUM_VALUE( pluckMandore, "pluck.mandore" ) \
        MX_ENUM_VALUE( pluckMarovany, "pluck.marovany" ) \
        MX_ENUM_VALUE( pluckMusicalBow, "pluck.musical-bow" ) \
        MX_ENUM_VALUE( pluckNgoni, "pluck.ngoni" ) \
        MX_ENUM_VALUE( pluckOud, "pluck.oud" ) \
        MX_ENUM_VALUE( pluckPipa, "pluck.pipa" ) \
        MX_ENUM_VALUE( pluckPsaltery, "pluck.psaltery" ) \
        MX_ENUM_VALUE( pluckRuan, "pluck.ruan" ) \
        MX_ENUM_VALUE( pluckSallaneh, "pluck.sallaneh" ) \
        MX_ENUM_VALUE( pluckSanshin, "pluck.sanshin" ) \
        MX_ENUM_VALUE( pluckSantoor, "pluck.santoor" ) \
        MX_ENUM_VALUE( pluckSanxian, "pluck.sanxian" ) \
        MX_ENUM_VALUE( pluckSarod, "pluck.sarod" ) \
        MX_ENUM_VALUE( pluckSaung, "pluck.saung" ) \
        MX_ENUM_VALUE( pluckSaz, "pluck.saz" ) \
        MX_ENUM_VALUE( pluckSe, "pluck.se" ) \
        MX_ENUM_VALUE( pluckSetar, "pluck.setar" ) \
        MX_ENUM_VALUE( pluckShamisen, "pluck.shamisen" ) \
        MX_ENUM_VALUE( pluckSitar, "pluck.sitar" ) \
        MX_ENUM_VALUE( pluckSynth, "pluck.synth" ) \
        MX_ENUM_VALUE( pluckSynthCharang, "pluck.synth.charang" ) \
        MX_ENUM_VALUE( pluckSynthChiff, "pluck.synth.chiff" ) \
        MX_ENUM_VALUE( pluckSynthStick, "pluck.synth.stick" ) \
        MX_ENUM_VALUE( pluckTambura, "pluck.tambura" ) \
        MX_ENUM_VALUE( pluckTamburaBulgarian, "pluck.tambura.bulgarian" ) \
        MX_ENUM_VALUE( pluckTamburaFemale, "pluck.tambura.female" ) \
        MX_ENUM_VALUE( pluckTamburaMale, "pluck.tambura.male" ) \
        MX_ENUM_VALUE( pluckTar, "pluck.tar" ) \
        MX_ENUM_VALUE( pluckTheorbo, "pluck.theorbo" ) \
        MX_ENUM_VALUE( pluckTimple, "pluck.timple" ) \
        MX_ENUM_VALUE( pluckTiple, "pluck.tiple" ) \
        MX_ENUM_VALUE( pluckTres, "pluck.tres" ) \
        MX_ENUM_VALUE( pluckUkulele, "pluck.ukulele" ) \
        MX_ENUM_VALUE( pluckUkuleleTenor, "pluck.ukulele.tenor" ) \
        MX_ENUM_VALUE( pluckValiha, "pluck.valiha" ) \
        MX_ENUM_VALUE( pluckVeena, "pluck.veena" ) \
        MX_ENUM_VALUE( pluckVeenaMohan, "pluck.veena.mohan" ) \
        MX_ENUM_VALUE( pluckVeenaRudra, "pluck.veena.rudra" ) \
        MX_ENUM_VALUE( pluckVeenaVichitra, "pluck.veena.vichitra" ) \
        MX_ENUM_VALUE( pluckVihuela, "pluck.vihuela" ) \
        MX_ENUM_VALUE( pluckVihuelaMexican, "pluck.vihuela.mexican" ) \
        MX_ENUM_VALUE( pluckXalam, "pluck.xalam" ) \
        MX_ENUM_VALUE( pluckYueqin, "pluck.yueqin" ) \
        MX_ENUM_VALUE( pluckZither, "pluck.zither" ) \
        MX_ENUM_VALUE( pluckZitherOvertone, "pluck.zither.overtone" ) \
        MX_ENUM_VALUE( rattleAfoxe, "rattle.afoxe" ) \
        MX_ENUM_VALUE( rattleBirds, "rattle.birds" ) \
        MX_ENUM_VALUE( rattleCabasa, "rattle.cabasa" ) \
        MX_ENUM_VALUE( rattleCaxixi, "rattle.caxixi" ) \
        MX_ENUM_VALUE( rattleCog, "rattle.cog" ) \
        MX_ENUM_VALUE( rattleGanza, "rattle.ganza" ) \
        MX_ENUM_VALUE( rattleHosho, "rattle.hosho" ) \
        MX_ENUM_VALUE( rattleJawbone, "rattle.jawbone" ) \
        MX_ENUM_VALUE( rattleKayamba, "rattle.kayamba" ) \
        MX_ENUM_VALUE( rattleKpokoKpoko, "rattle.kpoko-kpoko" ) \
        MX_ENUM_VALUE( rattleLavaStones, "rattle.lava-stones" ) \
        MX_ENUM_VALUE( rattleMaraca, "rattle.maraca" ) \
        MX_ENUM_VALUE( rattleRainStick, "rattle.rain-stick" ) \
        MX_ENUM_VALUE( rattleRatchet, "rattle.ratchet" ) \
        MX_ENUM_VALUE( rattleRattle, "rattle.rattle" ) \
        MX_ENUM_VALUE( rattleShaker, "rattle.shaker" ) \
        MX_ENUM_VALUE( rattleShakerEgg, "rattle.shaker.egg" ) \
        MX_ENUM_VALUE( rattleShekere, "rattle.shekere" ) \
        MX_ENUM_VALUE( rattleSistre, "rattle.sistre" ) \
        MX_ENUM_VALUE( rattleTelevi, "rattle.televi" ) \
        MX_ENUM_VALUE( rattleVibraslap, "rattle.vibraslap" ) \
        MX_ENUM_VALUE( rattleWasembe, "rattle.wasembe" ) \
        MX_ENUM_VALUE( stringsAjaeng, "strings.ajaeng" ) \
        MX_ENUM_VALUE( stringsArpeggione, "strings.arpeggione" ) \
        MX_ENUM_VALUE( stringsBaryton, "strings.baryton" ) \
        MX_ENUM_VALUE( stringsCello, "strings.cello" ) \
        MX_ENUM_VALUE( stringsCelloPiccolo, "strings.cello.piccolo" ) \
        MX_ENUM_VALUE( stringsContrabass, "strings.contrabass" ) \
        MX_ENUM_VALUE( stringsCrwth, "strings.crwth" ) \
        MX_ENUM_VALUE( stringsDanGao, "strings.dan-gao" ) \
        MX_ENUM_VALUE( stringsDihu, "strings.dihu" ) \
        MX_ENUM_VALUE( stringsErhu, "strings.erhu" ) \
        MX_ENUM_VALUE( stringsErxian, "strings.erxian" ) \
        MX_ENUM_VALUE( stringsEsraj, "strings.esraj" ) \
        MX_ENUM_VALUE( stringsFiddle, "strings.fiddle" ) \
        MX_ENUM_VALUE( stringsFiddleHardanger, "strings.fiddle.hardanger" ) \
        MX_ENUM_VALUE( stringsGadulka, "strings.gadulka" ) \
        MX_ENUM_VALUE( stringsGaohu, "strings.gaohu" ) \
        MX_ENUM_VALUE( stringsGehu, "strings.gehu" ) \
        MX_ENUM_VALUE( stringsGroup, "strings.group" ) \
        MX_ENUM_VALUE( stringsGroupSynth, "strings.group.synth" ) \
        MX_ENUM_VALUE( stringsHaegeum, "strings.haegeum" ) \
        MX_ENUM_VALUE( stringsHurdyGurdy, "strings.hurdy-gurdy" ) \
        MX_ENUM_VALUE( stringsIgil, "strings.igil" ) \
        MX_ENUM_VALUE( stringsKamancha, "strings.kamancha" ) \
        MX_ENUM_VALUE( stringsKokyu, "strings.kokyu" ) \
        MX_ENUM_VALUE( stringsLaruan, "strings.laruan" ) \
        MX_ENUM_VALUE( stringsLeiqin, "strings.leiqin" ) \
        MX_ENUM_VALUE( stringsLirone, "strings.lirone" ) \
        MX_ENUM_VALUE( stringsLyraByzantine, "strings.lyra.byzantine" ) \
        MX_ENUM_VALUE( stringsLyraCretan, "strings.lyra.cretan" ) \
        MX_ENUM_VALUE( stringsMorinKhuur, "strings.morin-khuur" ) \
        MX_ENUM_VALUE( stringsNyckelharpa, "strings.nyckelharpa" ) \
        MX_ENUM_VALUE( stringsOctobass, "strings.octobass" ) \
        MX_ENUM_VALUE( stringsRebab, "strings.rebab" ) \
        MX_ENUM_VALUE( stringsRebec, "strings.rebec" ) \
        MX_ENUM_VALUE( stringsSarangi, "strings.sarangi" ) \
        MX_ENUM_VALUE( stringsStrohViolin, "strings.stroh-violin" ) \
        MX_ENUM_VALUE( stringsTrombaMarina, "strings.tromba-marina" ) \
        MX_ENUM_VALUE( stringsVielle, "strings.vielle" ) \
        MX_ENUM_VALUE( stringsViol, "strings.viol" ) \
        MX_ENUM_VALUE( stringsViolAlto, "strings.viol.alto" ) \
        MX_ENUM_VALUE( stringsViolBass, "strings.viol.bass" ) \
        MX_ENUM_VALUE( stringsViolTenor, "strings.viol.tenor" ) \
        MX_ENUM_VALUE( stringsViolTreble, "strings.viol.treble" ) \
        MX_ENUM_VALUE( stringsViolViolone, "strings.viol.violone" ) \
        MX_ENUM_VALUE( stringsViola, "strings.viola" ) \
        MX_ENUM_VALUE( stringsViolaDamore, "strings.viola-damore" ) \
        MX_ENUM_VALUE( stringsViolin, "strings.violin" ) \
        MX_ENUM_VALUE( stringsViolonoPiccolo, "strings.violono.piccolo" ) \
        MX_ENUM_VALUE( stringsViolotta, "strings.violotta" ) \
        MX_ENUM_VALUE( stringsYayliTanbur, "strings.yayli-tanbur" ) \
        MX_ENUM_VALUE( stringsYazheng, "strings.yazheng" ) \
        MX_ENUM_VALUE( stringsZhonghu, "strings.zhonghu" ) \
        MX_ENUM_VALUE( synthEffects, "synth.effects" ) \
        MX_ENUM_VALUE( synthEffectsAtmosphere, "synth.effects.atmosphere" ) \
        MX_ENUM_VALUE( synthEffectsBrightness, "synth.effects.brightness" ) \
        MX_ENUM_VALUE( synthEffectsCrystal, "synth.effects.crystal" ) \
        MX_ENUM_VALUE( synthEffectsEchoes, "synth.effects.echoes" ) \
        MX_ENUM_VALUE( synthEffectsGoblins, "synth.effects.goblins" ) \
        MX_ENUM_VALUE( synthEffectsRain, "synth.effects.rain" ) \
        MX_ENUM_VALUE( synthEffectsSciFi, "synth.effects.sci-fi" ) \
        MX_ENUM_VALUE( synthEffectsSoundtrack, "synth.effects.soundtrack" ) \
        MX_ENUM_VALUE( synthGroup, "synth.group" ) \
        MX_ENUM_VALUE( synthGroupFifths, "synth.group.fifths" ) \
        MX_ENUM_VALUE( synthGroupOrchestra, "synth.group.orchestra" ) \
        MX_ENUM_VALUE( synthPad, "synth.pad" ) \
        MX_ENUM_VALUE( synthPadBowed, "synth.pad.bowed" ) \
        MX_ENUM_VALUE( synthPadChoir, "synth.pad.choir" ) \
        MX_ENUM_VALUE( synthPadHalo, "synth.pad.halo" ) \
        MX_ENUM_VALUE( synthPadMetallic, "synth.pad.metallic" ) \
        MX_ENUM_VALUE( synthPadPolysynth, "synth.pad.polysynth" ) \
        MX_ENUM_VALUE( synthPadSweep, "synth.pad.sweep" ) \
        MX_ENUM_VALUE( synthPadWarm, "synth.pad.warm" ) \
        MX_ENUM_VALUE( synthTheremin, "synth.theremin" ) \
        MX_ENUM_VALUE( synthToneSawtooth, "synth.tone.sawtooth" ) \
        MX_ENUM_VALUE( synthToneSine, "synth.tone.sine" ) \
        MX_ENUM_VALUE( synthToneSquare, "synth.tone.square" ) \
        MX_ENUM_VALUE( voiceAa, "voice.aa" ) \
        MX_ENUM_VALUE( voiceAlto, "voice.alto" ) \
        MX_ENUM_VALUE( voiceAw, "voice.aw" ) \
        MX_ENUM_VALUE( voiceBaritone, "voice.baritone" ) \
        MX_ENUM_VALUE( voiceBass, "voice.bass" ) \
        MX_ENUM_VALUE( voiceChild, "voice.child" ) \
        MX_ENUM_VALUE( voiceCountertenor, "voice.countertenor" ) \
        MX_ENUM_VALUE( voiceDoo, "voice.doo" ) \
        MX_ENUM_VALUE( voiceEe, "voice.ee" ) \
        MX_ENUM_VALUE( voiceFemale, "voice.female" ) \
        MX_ENUM_VALUE( voiceKazoo, "voice.kazoo" ) \
        MX_ENUM_VALUE( voiceMale, "voice.male" ) \
        MX_ENUM_VALUE( voiceMezzoSoprano, "voice.mezzo-soprano" ) \
        MX_ENUM_VALUE( voiceMm, "voice.mm" ) \
        MX_ENUM_VALUE( voiceOo, "voice.oo" ) \
        MX_ENUM_VALUE( voicePercussion, "voice.percussion" ) \
        MX_ENUM_VALUE( voicePercussionBeatbox, "voice.percussion.beatbox" ) \
        MX_ENUM_VALUE( voiceSoprano, "voice.soprano" ) \
        MX_ENUM_VALUE( voiceSynth, "voice.synth" ) \
        MX_ENUM_VALUE( voiceTalkBox, "voice.talk-box" ) \
        MX_ENUM_VALUE( voiceTenor, "voice.tenor" ) \
        MX_ENUM_VALUE( voiceVocals, "voice.vocals" ) \
        MX_ENUM_VALUE( windFlutesBansuri, "wind.flutes.bansuri" ) \
        MX_ENUM_VALUE( windFlutesBlownBottle, "wind.flutes.blown-bottle" ) \
        MX_ENUM_VALUE( windFlutesCalliope, "wind.flutes.calliope" ) \
        MX_ENUM_VALUE( windFlutesDanso, "wind.flutes.danso" ) \
        MX_ENUM_VALUE( windFlutesDiZi, "wind.flutes.di-zi" ) \
        MX_ENUM_VALUE( windFlutesDvojnice, "wind.flutes.dvojnice" ) \
        MX_ENUM_VALUE( windFlutesFife, "wind.flutes.fife" ) \
        MX_ENUM_VALUE( windFlutesFlageolet, "wind.flutes.flageolet" ) \
        MX_ENUM_VALUE( windFlutesFlute, "wind.flutes.flute" ) \
        MX_ENUM_VALUE( windFlutesFluteAlto, "wind.flutes.flute.alto" ) \
        MX_ENUM_VALUE( windFlutesFluteBass, "wind.flutes.flute.bass" ) \
        MX_ENUM_VALUE( windFlutesFluteContraAlto, "wind.flutes.flute.contra-alto" ) \
        MX_ENUM_VALUE( windFlutesFluteContrabass, "wind.flutes.flute.contrabass" ) \
        MX_ENUM_VALUE( windFlutesFluteDoubleContrabass, "wind.flutes.flute.double-contrabass" ) \
        MX_ENUM_VALUE( windFlutesFluteIrish, "wind.flutes.flute.irish" ) \
        MX_ENUM_VALUE( windFlutesFlutePiccolo, "wind.flutes.flute.piccolo" ) \
        MX_ENUM_VALUE( windFlutesFluteSubcontrabass, "wind.flutes.flute.subcontrabass" ) \
        MX_ENUM_VALUE( windFlutesFujara, "wind.flutes.fujara" ) \
        MX_ENUM_VALUE( windFlutesGemshorn, "wind.flutes.gemshorn" ) \
        MX_ENUM_VALUE( windFlutesHocchiku, "wind.flutes.hocchiku" ) \
        MX_ENUM_VALUE( windFlutesHun, "wind.flutes.hun" ) \
        MX_ENUM_VALUE( windFlutesKaval, "wind.flutes.kaval" ) \
        MX_ENUM_VALUE( windFlutesKawala, "wind.flutes.kawala" ) \
        MX_ENUM_VALUE( windFlutesKhlui, "wind.flutes.khlui" ) \
        MX_ENUM_VALUE( windFlutesKnotweed, "wind.flutes.knotweed" ) \
        MX_ENUM_VALUE( windFlutesKoncovkaAlto, "wind.flutes.koncovka.alto" ) \
        MX_ENUM_VALUE( windFlutesKoudi, "wind.flutes.koudi" ) \
        MX_ENUM_VALUE( windFlutesNey, "wind.flutes.ney" ) \
        MX_ENUM_VALUE( windFlutesNohkan, "wind.flutes.nohkan" ) \
        MX_ENUM_VALUE( windFlutesNose, "wind.flutes.nose" ) \
        MX_ENUM_VALUE( windFlutesOcarina, "wind.flutes.ocarina" ) \
        MX_ENUM_VALUE( windFlutesOvertoneTenor, "wind.flutes.overtone.tenor" ) \
        MX_ENUM_VALUE( windFlutesPalendag, "wind.flutes.palendag" ) \
        MX_ENUM_VALUE( windFlutesPanpipes, "wind.flutes.panpipes" ) \
        MX_ENUM_VALUE( windFlutesQuena, "wind.flutes.quena" ) \
        MX_ENUM_VALUE( windFlutesRecorder, "wind.flutes.recorder" ) \
        MX_ENUM_VALUE( windFlutesRecorderAlto, "wind.flutes.recorder.alto" ) \
        MX_ENUM_VALUE( windFlutesRecorderBass, "wind.flutes.recorder.bass" ) \
        MX_ENUM_VALUE( windFlutesRecorderContrabass, "wind.flutes.recorder.contrabass" ) \
        MX_ENUM_VALUE( windFlutesRecorderDescant, "wind.flutes.recorder.descant" ) \
        MX_ENUM_VALUE( windFlutesRecorderGarklein, "wind.flutes.recorder.garklein" ) \
        MX_ENUM_VALUE( windFlutesRecorderGreatBass, "wind.flutes.recorder.great-bass" ) \
        MX_ENUM_VALUE( windFlutesRecorderSopranino, "wind.flutes.recorder.sopranino" ) \
        MX_ENUM_VALUE( windFlutesRecorderSoprano, "wind.flutes.recorder.soprano" ) \
        MX_ENUM_VALUE( windFlutesRecorderTenor, "wind.flutes.recorder.tenor" ) \
        MX_ENUM_VALUE( windFlutesRyuteki, "wind.flutes.ryuteki" ) \
        MX_ENUM_VALUE( windFlutesShakuhachi, "wind.flutes.shakuhachi" ) \
        MX_ENUM_VALUE( windFlutesShepherdsPipe, "wind.flutes.shepherds-pipe" ) \
        MX_ENUM_VALUE( windFlutesShinobue, "wind.flutes.shinobue" ) \
        MX_ENUM_VALUE( windFlutesShvi, "wind.flutes.shvi" ) \
        MX_ENUM_VALUE( windFlutesSuling, "wind.flutes.suling" ) \
        MX_ENUM_VALUE( windFlutesTarka, "wind.flutes.tarka" ) \
        MX_ENUM_VALUE( windFlutesTumpong, "wind.flutes.tumpong" ) \
        MX_ENUM_VALUE( windFlutesVenu, "wind.flutes.venu" ) \
        MX_ENUM_VALUE( windFlutesWhistle, "wind.flutes.whistle" ) \
        MX_ENUM_VALUE( windFlutesWhistleAlto, "wind.flutes.whistle.alto" ) \
        MX_ENUM_VALUE( windFlutesWhistleLowIrish, "wind.flutes.whistle.low-irish" ) \
        MX_ENUM_VALUE( windFlutesWhistleShiva, "wind.flutes.whistle.shiva" ) \
        MX_ENUM_VALUE( windFlutesWhistleSlide, "wind.flutes.whistle.slide" ) \
        MX_ENUM_VALUE( windFlutesWhistleTin, "wind.flutes.whistle.tin" ) \
        MX_ENUM_VALUE( windFlutesWhistleTinBflat, "wind.flutes.whistle.tin.bflat" ) \
        MX_ENUM_VALUE( windFlutesWhistleTinD, "wind.flutes.whistle.tin.d" ) \
        MX_ENUM_VALUE( windFlutesXiao, "wind.flutes.xiao" ) \
        MX_ENUM_VALUE( windFlutesXun, "wind.flutes.xun" ) \
        MX_ENUM_VALUE( windGroup, "wind.group" ) \
        MX_ENUM_VALUE( windJug, "wind.jug" ) \
        MX_ENUM_VALUE( windPipesBagpipes, "wind.pipes.bagpipes" ) \
        MX_ENUM_VALUE( windPipesGaida, "wind.pipes.gaida" ) \
        MX_ENUM_VALUE( windPipesHighland, "wind.pipes.highland" ) \
        MX_ENUM_VALUE( windPipesUilleann, "wind.pipes.uilleann" ) \
        MX_ENUM_VALUE( windPungi, "wind.pungi" ) \
        MX_ENUM_VALUE( windReedAlbogue, "wind.reed.albogue" ) \
        MX_ENUM_VALUE( windReedAlboka, "wind.reed.alboka" ) \
        MX_ENUM_VALUE( windReedAlgaita, "wind.reed.algaita" ) \
        MX_ENUM_VALUE( windReedArghul, "wind.reed.arghul" ) \
        MX_ENUM_VALUE( windReedBassetHorn, "wind.reed.basset-horn" ) \
        MX_ENUM_VALUE( windReedBassoon, "wind.reed.bassoon" ) \
        MX_ENUM_VALUE( windReedBawu, "wind.reed.bawu" ) \
        MX_ENUM_VALUE( windReedBifora, "wind.reed.bifora" ) \
        MX_ENUM_VALUE( windReedBombarde, "wind.reed.bombarde" ) \
        MX_ENUM_VALUE( windReedChalumeau, "wind.reed.chalumeau" ) \
        MX_ENUM_VALUE( windReedClarinet, "wind.reed.clarinet" ) \
        MX_ENUM_VALUE( windReedClarinetA, "wind.reed.clarinet.a" ) \
        MX_ENUM_VALUE( windReedClarinetAlto, "wind.reed.clarinet.alto" ) \
        MX_ENUM_VALUE( windReedClarinetBass, "wind.reed.clarinet.bass" ) \
        MX_ENUM_VALUE( windReedClarinetBasset, "wind.reed.clarinet.basset" ) \
        MX_ENUM_VALUE( windReedClarinetBflat, "wind.reed.clarinet.bflat" ) \
        MX_ENUM_VALUE( windReedClarinetContraAlto, "wind.reed.clarinet.contra-alto" ) \
        MX_ENUM_VALUE( windReedClarinetContrabass, "wind.reed.clarinet.contrabass" ) \
        MX_ENUM_VALUE( windReedClarinetEflat, "wind.reed.clarinet.eflat" ) \
        MX_ENUM_VALUE( windReedClarinetPiccoloAflat, "wind.reed.clarinet.piccolo.aflat" ) \
        MX_ENUM_VALUE( windReedClarinetteDamour, "wind.reed.clarinette-damour" ) \
        MX_ENUM_VALUE( windReedContrabass, "wind.reed.contrabass" ) \
        MX_ENUM_VALUE( windReedContrabassoon, "wind.reed.contrabassoon" ) \
        MX_ENUM_VALUE( windReedCornamuse, "wind.reed.cornamuse" ) \
        MX_ENUM_VALUE( windReedCromorne, "wind.reed.cromorne" ) \
        MX_ENUM_VALUE( windReedCrumhorn, "wind.reed.crumhorn" ) \
        MX_ENUM_VALUE( windReedCrumhornAlto, "wind.reed.crumhorn.alto" ) \
        MX_ENUM_VALUE( windReedCrumhornBass, "wind.reed.crumhorn.bass" ) \
        MX_ENUM_VALUE( windReedCrumhornGreatBass, "wind.reed.crumhorn.great-bass" ) \
        MX_ENUM_VALUE( windReedCrumhornSoprano, "wind.reed.crumhorn.soprano" ) \
        MX_ENUM_VALUE( windReedCrumhornTenor, "wind.reed.crumhorn.tenor" ) \
        MX_ENUM_VALUE( windReedDiple, "wind.reed.diple" ) \
        MX_ENUM_VALUE( windReedDiplica, "wind.reed.diplica" ) \
        MX_ENUM_VALUE( windReedDuduk, "wind.reed.duduk" ) \
        MX_ENUM_VALUE( windReedDulcian, "wind.reed.dulcian" ) \
        MX_ENUM_VALUE( windReedDulzaina, "wind.reed.dulzaina" ) \
        MX_ENUM_VALUE( windReedEnglishHorn, "wind.reed.english-horn" ) \
        MX_ENUM_VALUE( windReedGuanzi, "wind.reed.guanzi" ) \
        MX_ENUM_VALUE( windReedHarmonica, "wind.reed.harmonica" ) \
        MX_ENUM_VALUE( windReedHarmonicaBass, "wind.reed.harmonica.bass" ) \
        MX_ENUM_VALUE( windReedHeckelClarina, "wind.reed.heckel-clarina" ) \
        MX_ENUM_VALUE( windReedHeckelphone, "wind.reed.heckelphone" ) \
        MX_ENUM_VALUE( windReedHeckelphonePiccolo, "wind.reed.heckelphone.piccolo" ) \
        MX_ENUM_VALUE( windReedHeckelphoneClarinet, "wind.reed.heckelphone-clarinet" ) \
        MX_ENUM_VALUE( windReedHichiriki, "wind.reed.hichiriki" ) \
        MX_ENUM_VALUE( windReedHirtenschalmei, "wind.reed.hirtenschalmei" ) \
        MX_ENUM_VALUE( windReedHne, "wind.reed.hne" ) \
        MX_ENUM_VALUE( windReedHornpipe, "wind.reed.hornpipe" ) \
        MX_ENUM_VALUE( windReedHouguan, "wind.reed.houguan" ) \
        MX_ENUM_VALUE( windReedHulusi, "wind.reed.hulusi" ) \
        MX_ENUM_VALUE( windReedJogiBaja, "wind.reed.jogi-baja" ) \
        MX_ENUM_VALUE( windReedKenBau, "wind.reed.ken-bau" ) \
        MX_ENUM_VALUE( windReedKhaenMouthOrgan, "wind.reed.khaen-mouth-organ" ) \
        MX_ENUM_VALUE( windReedLauneddas, "wind.reed.launeddas" ) \
        MX_ENUM_VALUE( windReedMaqrunah, "wind.reed.maqrunah" ) \
        MX_ENUM_VALUE( windReedMelodica, "wind.reed.melodica" ) \
        MX_ENUM_VALUE( windReedMijwiz, "wind.reed.mijwiz" ) \
        MX_ENUM_VALUE( windReedMizmar, "wind.reed.mizmar" ) \
        MX_ENUM_VALUE( windReedNadaswaram, "wind.reed.nadaswaram" ) \
        MX_ENUM_VALUE( windReedOboe, "wind.reed.oboe" ) \
        MX_ENUM_VALUE( windReedOboeBass, "wind.reed.oboe.bass" ) \
        MX_ENUM_VALUE( windReedOboePiccolo, "wind.reed.oboe.piccolo" ) \
        MX_ENUM_VALUE( windReedOboeDaCaccia, "wind.reed.oboe-da-caccia" ) \
        MX_ENUM_VALUE( windReedOboeDamore, "wind.reed.oboe-damore" ) \
        MX_ENUM_VALUE( windReedOctavin, "wind.reed.octavin" ) \
        MX_ENUM_VALUE( windReedPi, "wind.reed.pi" ) \
        MX_ENUM_VALUE( windReedPibgorn, "wind.reed.pibgorn" ) \
        MX_ENUM_VALUE( windReedPiri, "wind.reed.piri" ) \
        MX_ENUM_VALUE( windReedRackett, "wind.reed.rackett" ) \
        MX_ENUM_VALUE( windReedRauschpfeife, "wind.reed.rauschpfeife" ) \
        MX_ENUM_VALUE( windReedRhaita, "wind.reed.rhaita" ) \
        MX_ENUM_VALUE( windReedRothphone, "wind.reed.rothphone" ) \
        MX_ENUM_VALUE( windReedSarrusaphone, "wind.reed.sarrusaphone" ) \
        MX_ENUM_VALUE( windReedSaxonette, "wind.reed.saxonette" ) \
        MX_ENUM_VALUE( windReedSaxophone, "wind.reed.saxophone" ) \
        MX_ENUM_VALUE( windReedSaxophoneAlto, "wind.reed.saxophone.alto" ) \
        MX_ENUM_VALUE( windReedSaxophoneAulochrome, "wind.reed.saxophone.aulochrome" ) \
        MX_ENUM_VALUE( windReedSaxophoneBaritone, "wind.reed.saxophone.baritone" ) \
        MX_ENUM_VALUE( windReedSaxophoneBass, "wind.reed.saxophone.bass" ) \
        MX_ENUM_VALUE( windReedSaxophoneContrabass, "wind.reed.saxophone.contrabass" ) \
        MX_ENUM_VALUE( windReedSaxophoneMelody, "wind.reed.saxophone.melody" ) \
        MX_ENUM_VALUE( windReedSaxophoneMezzoSoprano, "wind.reed.saxophone.mezzo-soprano" ) \
        MX_ENUM_VALUE( windReedSaxophoneSopranino, "wind.reed.saxophone.sopranino" ) \
        MX_ENUM_VALUE( windReedSaxophoneSopranissimo, "wind.reed.saxophone.sopranissimo" ) \
        MX_ENUM_VALUE( windReedSaxophoneSoprano, "wind.reed.saxophone.soprano" ) \
        MX_ENUM_VALUE( windReedSaxophoneSubcontrabass, "wind.reed.saxophone.subcontrabass" ) \
        MX_ENUM_VALUE( windReedSaxophoneTenor, "wind.reed.saxophone.tenor" ) \
        MX_ENUM_VALUE( windReedShawm, "wind.reed.shawm" ) \
        MX_ENUM_VALUE( windReedShenai, "wind.reed.shenai" ) \
        MX_ENUM_VALUE( windReedSheng, "wind.reed.sheng" ) \
        MX_ENUM_VALUE( windReedSipsi, "wind.reed.sipsi" ) \
        MX_ENUM_VALUE( windReedSopila, "wind.reed.sopila" ) \
        MX_ENUM_VALUE( windReedSorna, "wind.reed.sorna" ) \
        MX_ENUM_VALUE( windReedSralai, "wind.reed.sralai" ) \
        MX_ENUM_VALUE( windReedSuona, "wind.reed.suona" ) \
        MX_ENUM_VALUE( windReedSurnai, "wind.reed.surnai" ) \
        MX_ENUM_VALUE( windReedTaepyeongso, "wind.reed.taepyeongso" ) \
        MX_ENUM_VALUE( windReedTarogato, "wind.reed.tarogato" ) \
        MX_ENUM_VALUE( windReedTarogatoAncient, "wind.reed.tarogato.ancient" ) \
        MX_ENUM_VALUE( windReedTrompetaChina, "wind.reed.trompeta-china" ) \
        MX_ENUM_VALUE( windReedTubax, "wind.reed.tubax" ) \
        MX_ENUM_VALUE( windReedXaphoon, "wind.reed.xaphoon" ) \
        MX_ENUM_VALUE( windReedZhaleika, "wind.reed.zhaleika" ) \
        MX_ENUM_VALUE( windReedZurla, "wind.reed.zurla" ) \
        MX_ENUM_VALUE( windReedZurna, "wind.reed.zurna" ) \
        MX_ENUM_VALUE( woodAgogoBlock, "wood.agogo-block" ) \
        MX_ENUM_VALUE( woodAgungATamlang, "wood.agung-a-tamlang" ) \
        MX_ENUM_VALUE( woodAhoko, "wood.ahoko" ) \
        MX_ENUM_VALUE( woodBones, "wood.bones" ) \
        MX_ENUM_VALUE( woodCastanets, "wood.castanets" ) \
        MX_ENUM_VALUE( woodClaves, "wood.claves" ) \
        MX_ENUM_VALUE( woodDrumSticks, "wood.drum-sticks" ) \
        MX_ENUM_VALUE( woodGourd, "wood.gourd" ) \
        MX_ENUM_VALUE( woodGraniteBlock, "wood.granite-block" ) \
        MX_ENUM_VALUE( woodGuban, "wood.guban" ) \
        MX_ENUM_VALUE( woodGuiro, "wood.guiro" ) \
        MX_ENUM_VALUE( woodHyoushigi, "wood.hyoushigi" ) \
        MX_ENUM_VALUE( woodIpu, "wood.ipu" ) \
        MX_ENUM_VALUE( woodJamBlock, "wood.jam-block" ) \
        MX_ENUM_VALUE( woodKaekeeke, "wood.kaekeeke" ) \
        MX_ENUM_VALUE( woodKagul, "wood.kagul" ) \
        MX_ENUM_VALUE( woodKalaau, "wood.kalaau" ) \
        MX_ENUM_VALUE( woodKashiklar, "wood.kashiklar" ) \
        MX_ENUM_VALUE( woodKubing, "wood.kubing" ) \
        MX_ENUM_VALUE( woodPanClappers, "wood.pan-clappers" ) \
        MX_ENUM_VALUE( woodSandBlock, "wood.sand-block" ) \
        MX_ENUM_VALUE( woodSlapstick, "wood.slapstick" ) \
        MX_ENUM_VALUE( woodStirDrum, "wood.stir-drum" ) \
        MX_ENUM_VALUE( woodTempleBlock, "wood.temple-block" ) \
        MX_ENUM_VALUE( woodTicTocBlock, "wood.tic-toc-block" ) \
        MX_ENUM_VALUE( woodTonetang, "wood.tonetang" ) \
        MX_ENUM_VALUE( woodWoodBlock, "wood.wood-block" ) \

        #include "mx/utility/EnumWithString.h"
        #undef MX_ENUM_CLASS_NAME
        #undef MX_ENUM_VALUE
        #undef MX_ENUM_MEMBERS
    }
}
