#pragma once

// TODO this needs to be autogenerated by cmake

namespace MxTest
{

#ifdef _MSC_VER
    constexpr const char* const RESOURCES_DIRECTORY_PATH = "C:\\gt\\MxRepo\\Resources\\";
    constexpr const char FILE_PATH_SEPARATOR = '\\';
#else
    constexpr const char* const RESOURCES_DIRECTORY_PATH = "/Volumes/Macintosh HD/Users/mjb/Dropbox/Programming/MxRepo/Resources/";
    constexpr const char FILE_PATH_SEPARATOR = '/';
#endif
    

}