// This file is auto generated by CMake
// To override these paths, pass in macro definitions to the compiler.
#pragma once

// The absolute path to the root of the repository.
#ifndef MX_REPO_ROOT_PATH
#define MX_REPO_ROOT_PATH "/Users/brigmatt/repos/mx"
#endif

// The absolute path to the binary output directory.
#ifndef MX_BINARY_OUTPUT_PATH
#define MX_BINARY_OUTPUT_PATH "/Users/brigmatt/repos/mx/cmake-build-debug"
#endif