// MusicXML Class Library
// Copyright (c) by Matthew James Briggs
// Distributed under the MIT License

#pragma once

// TODO this needs to be autogenerated by cmake

namespace mxtest
{

#ifdef _MSC_VER
    constexpr const char* const RESOURCES_DIRECTORY_PATH = "E:\\User\\Documents\\MxRepo\\Resources\\";
    constexpr const char FILE_PATH_SEPARATOR = '\\';
#else
    constexpr const char* const RESOURCES_DIRECTORY_PATH = "/Volumes/Macintosh HD/Users/mjb/Dropbox/Programming/MxRepo/Resources/";
    constexpr const char FILE_PATH_SEPARATOR = '/';
#endif

}
